<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/Arithmetics_Statistics_Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, True, False, True, False])

In [7]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 1.2, 2.3, 1.4, 2.5])

In [8]:
data = np.random.randn(6)
data

array([ 0.2113586 ,  0.87022012, -0.98798713, -1.45319232, -2.50186525,
        0.54486668])

In [9]:
np.sum(data)

-3.316599296226372

In [10]:
np.mean(data)

-0.552766549371062

In [11]:
np.cumsum(data)

array([ 0.2113586 ,  1.08157873,  0.09359159, -1.35960073, -3.86146597,
       -3.3165993 ])

In [12]:
np.cumprod(data)

array([ 0.2113586 ,  0.18392851, -0.181719  ,  0.26407266, -0.66067421,
       -0.35997936])

In [13]:
data = np.random.rand(6)

In [14]:
data

array([0.23243197, 0.51857391, 0.81133424, 0.5599864 , 0.90770145,
       0.39788887])

In [15]:
np.sort(data)

array([0.23243197, 0.39788887, 0.51857391, 0.5599864 , 0.81133424,
       0.90770145])

In [16]:
-np.sort(-data)

array([0.90770145, 0.81133424, 0.5599864 , 0.51857391, 0.39788887,
       0.23243197])

In [17]:
np.sort(-data)

array([-0.90770145, -0.81133424, -0.5599864 , -0.51857391, -0.39788887,
       -0.23243197])

In [19]:
data = np.random.rand(2, 3)

In [20]:
data

array([[0.07100192, 0.2405625 , 0.38940262],
       [0.36726412, 0.03218669, 0.39546407]])

In [21]:
np.sort(data, axis=0)

array([[0.07100192, 0.03218669, 0.38940262],
       [0.36726412, 0.2405625 , 0.39546407]])

In [22]:
np.sort(data, axis=1)

array([[0.07100192, 0.2405625 , 0.38940262],
       [0.03218669, 0.36726412, 0.39546407]])

In [23]:
-np.sort(-data, axis = 1)

array([[0.38940262, 0.2405625 , 0.07100192],
       [0.39546407, 0.36726412, 0.03218669]])

In [24]:
np.sort(data)

array([[0.07100192, 0.2405625 , 0.38940262],
       [0.03218669, 0.36726412, 0.39546407]])