<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
names = np.array(["Akbarjon", "Ahmadjon", "Aizmaxon", "Halimaxon", "Sobitxon"])

In [4]:
names

array(['Akbarjon', 'Ahmadjon', 'Aizmaxon', 'Halimaxon', 'Sobitxon'],
      dtype='<U9')

In [7]:
data = np.random.rand(5, 4)

In [12]:
data

array([[0.63516307, 0.74323362, 0.28322357, 0.83379843],
       [0.38597456, 0.96447421, 0.41159008, 0.5026807 ],
       [0.45222213, 0.1382129 , 0.07972541, 0.21734045],
       [0.57841704, 0.29910887, 0.89634323, 0.17522769],
       [0.03095646, 0.09834103, 0.13593101, 0.42933735]])

In [13]:
names == 'Akbarjon'

array([ True, False, False, False, False])

In [14]:
data[names == 'Akbarjon']

array([[0.63516307, 0.74323362, 0.28322357, 0.83379843]])

In [18]:
data[~(names == 'Akbarjon')]

array([[0.38597456, 0.96447421, 0.41159008, 0.5026807 ],
       [0.45222213, 0.1382129 , 0.07972541, 0.21734045],
       [0.57841704, 0.29910887, 0.89634323, 0.17522769],
       [0.03095646, 0.09834103, 0.13593101, 0.42933735]])

In [21]:
data[(names == 'Akbarjon') | (names == 'Ahmadjon')]

array([[0.63516307, 0.74323362, 0.28322357, 0.83379843],
       [0.38597456, 0.96447421, 0.41159008, 0.5026807 ]])

In [24]:
data[data < 1] = 1;

In [25]:
data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])