<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/ND_arryas_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [7]:
data1 = [2,3,4,5,3,5]
arr = np.array(data1)
print(arr)

[2 3 4 5 3 5]


In [8]:
arr

array([2, 3, 4, 5, 3, 5])

In [9]:
data2 = (12,4,3,235,234,5)
arr2 = np.array(data2)

In [10]:
arr2

array([ 12,   4,   3, 235, 234,   5])

In [11]:
arr.ndim # arr1 ning olchami not length

1

In [12]:
arr2.ndim # arr2 nig olchami not length

1

In [23]:
data3 = [[12,334324,345,345], [243,5,223,4], [1,2,3,4]]
arr3 = np.array(data3)

In [24]:
arr3

array([[    12, 334324,    345,    345],
       [   243,      5,    223,      4],
       [     1,      2,      3,      4]])

In [25]:
arr3.ndim

2

In [26]:
data4 = [[[123,321,213]]]

In [27]:
arr4 = np.array(data4)

In [28]:
arr4

array([[[123, 321, 213]]])

In [30]:
arr4.ndim

3

In [31]:
arr3

array([[    12, 334324,    345,    345],
       [   243,      5,    223,      4],
       [     1,      2,      3,      4]])

In [32]:
arr3.shape # qator va ustunlar soni

(3, 4)

In [33]:
arr3.size

12

In [36]:
arr4 = np.zeros((2, 4))

In [37]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
arr5 = np.ones((2,4))

In [41]:
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
arr5 = np.arange(4, 20, 2)

In [44]:
arr5

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
arr6 = np.arange(20)

In [46]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
arr7 = np.random.rand(2, 3)

In [51]:
arr7

array([[0.52809755, 0.10646138, 0.50718331],
       [0.99493121, 0.6849176 , 0.96594654]])

In [53]:
arr8 = np.random.randint(5, size = (2, 5))

In [54]:
arr8

array([[0, 4, 2, 1, 3],
       [2, 0, 4, 4, 4]])

In [55]:
arr9 = np.random.randn(2, 4)

In [56]:
arr9

array([[-2.17596942,  0.59129225,  1.28278301, -0.39840757],
       [-0.68450269,  0.40132487, -0.31712239, -0.52356017]])