<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/perceptron_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
def AND(x1, x2):
  w1, w2, b = 0.5, 0.5, 0.7
  signal = x1*w1 + x2*w2
  if signal <= b:
    return 0
  else:
    return 1

In [3]:
AND(1, 1)

1

In [4]:
AND(1, 0)

0

In [5]:
def NAND(x1, x2):
  w1, w2, b = -0.5, -0.5, -0.7
  signal = x1*w1 + x2*w2
  if signal <= b:
    return 0
  else:
    return 1

In [6]:
NAND(0,0)

1

In [7]:
NAND(1, 1)

0

In [14]:
def OR(x1, x2):
  w1, w2, b = 0.5, 0.5, 0.2
  signal = x1*w1 + x2*w2
  if signal <= b:
    return 0
  else:
    return 1

In [15]:
OR(1, 0)

1

In [16]:
OR(0,0)

0

In [17]:
def XOR(x1, x2):
  s1 = NAND(x1, x2)
  s2 = OR(x1, x2)
  s3 = AND(s1, s2)
  return s3

In [18]:
XOR(1, 1)

0

In [19]:
def step_function(x):
  if x <=0:
    return 0
  else:
    return 1

In [21]:
def step_matrix(x):
  return np.array(x>0, dtype=int)

In [20]:
x = [[0, 0], [0, 1], [1, 0], [1,1]]

In [28]:
def AND_matrix(x):
  w1, w2, b = 0.5, 0.5, -0.7
  w = np.array([[w1],[w2]])
  signal = np.dot(x, w) + b
  
  return step_matrix(signal)

In [29]:
AND_matrix(x)

array([[0],
       [0],
       [0],
       [1]])

In [36]:
def NAND_matrix(x):
  w1, w2, b = -0.5, -0.5, 0.7
  w = np.array([[w1],[w2]])
  signal = np.dot(x, w) + b
  
  return step_matrix(signal)


In [56]:
NAND_matrix(x)

array([[1],
       [1],
       [1],
       [0]])

In [38]:
def OR_matrix(x):
  w1, w2, b = 0.5, 0.5, -0.2
  w = np.array([[w1],[w2]])
  signal = np.dot(x, w) + b
  
  return step_matrix(signal)

In [55]:
OR_matrix(x)

array([[0],
       [1],
       [1],
       [1]])

In [50]:
np.concatenate((a, b), axis=1)

array([[0, 1],
       [1, 1],
       [1, 1],
       [1, 0]])

In [53]:
def XOR_matrix(x):
  s1 = NAND_matrix(x)
  s2 = OR_matrix(x)
  s3 = AND_matrix(np.concatenate((s1, s2), axis=1))
  return step_matrix(s3)

In [54]:
XOR_matrix(x)

array([[0],
       [1],
       [1],
       [0]])