<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/revision_np_pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np

In [12]:
m = np.array([[1,3],[2,3],[4,1]])

In [4]:
m

array([[1, 3],
       [2, 3],
       [4, 1]])

In [5]:
m.T

array([[1, 2, 4],
       [3, 3, 1]])

In [6]:
n = m.T

In [7]:
n

array([[1, 2, 4],
       [3, 3, 1]])

In [8]:
n.T

array([[1, 3],
       [2, 3],
       [4, 1]])

In [5]:
names = np.array(["a", "b", "c"])

In [6]:
names

array(['a', 'b', 'c'], dtype='<U1')

In [7]:
names == "a"

array([ True, False, False])

In [8]:
names[names == "a"]

array(['a'], dtype='<U1')

In [9]:
names

array(['a', 'b', 'c'], dtype='<U1')

In [11]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
s = np.dot(m, m.T)

In [15]:
s.T

array([[10, 11,  7],
       [11, 13, 11],
       [ 7, 11, 17]])

In [16]:
s

array([[10, 11,  7],
       [11, 13, 11],
       [ 7, 11, 17]])

In [4]:
import pandas as pd
s = pd.Series

In [5]:
names = s(['a', 'b', 'c'])

In [6]:
names

0    a
1    b
2    c
dtype: object

In [7]:
names.shape

(3,)

In [9]:
names.iloc[2]

'c'

In [10]:
names[2]

'c'

In [12]:
names.median

<bound method NDFrame._add_numeric_operations.<locals>.median of 0    a
1    b
2    c
dtype: object>

In [14]:
nums = s([1,2,3,4,5,5,6,67])

In [18]:
nums.median()

4.5

In [17]:
nums.mean()

11.625

In [19]:
nums.mode()

0    5
dtype: int64

In [28]:
california = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [31]:
california.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   
5    -119.56     36.51                37.0       1018.0           213.0   
6    -121.43     38.63                43.0       1009.0           225.0   
7    -120.65     35.48                19.0       2310.0           471.0   
8    -122.84     38.40                15.0       3080.0           617.0   
9    -118.02     34.08                31.0       2402.0           632.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  
5       663.0       204.0         1.6635             67000.0  
6       604.0       218.0         1.6641             67000.0  
7      1341.0       441.0         3.2250            166900.0  
8      1446.0       599.0         3.6696            194400.0  
9      2830.0       603.0         2.3333            164200.0

In [38]:
sm = california.iloc[:, :5].head(10)

In [39]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
0    -122.05     37.37                27.0       3885.0           661.0
1    -118.30     34.26                43.0       1510.0           310.0
2    -117.81     33.78                27.0       3589.0           507.0
3    -118.36     33.82                28.0         67.0            15.0
4    -119.67     36.33                19.0       1241.0           244.0
5    -119.56     36.51                37.0       1018.0           213.0
6    -121.43     38.63                43.0       1009.0           225.0
7    -120.65     35.48                19.0       2310.0           471.0
8    -122.84     38.40                15.0       3080.0           617.0
9    -118.02     34.08                31.0       2402.0           632.0

In [48]:
sm['deposit'] = np.NAN

In [49]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   
5    -119.56     36.51                37.0       1018.0           213.0   
6    -121.43     38.63                43.0       1009.0           225.0   
7    -120.65     35.48                19.0       2310.0           471.0   
8    -122.84     38.40                15.0       3080.0           617.0   
9    -118.02     34.08                31.0       2402.0           632.0   

   deposit  
0      NaN  
1      NaN  
2      NaN  
3      NaN  
4      NaN  
5      NaN  
6      NaN  
7      NaN  
8      NaN  
9      NaN

In [50]:
sm['deposit'] = 111

In [51]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   
5    -119.56     36.51                37.0       1018.0           213.0   
6    -121.43     38.63                43.0       1009.0           225.0   
7    -120.65     35.48                19.0       2310.0           471.0   
8    -122.84     38.40                15.0       3080.0           617.0   
9    -118.02     34.08                31.0       2402.0           632.0   

   deposit  
0      111  
1      111  
2      111  
3      111  
4      111  
5      111  
6      111  
7      111  
8      111  
9      111

In [58]:
sm.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [59]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
a    -122.05     37.37                27.0       3885.0           661.0   
b    -118.30     34.26                43.0       1510.0           310.0   
c    -117.81     33.78                27.0       3589.0           507.0   
d    -118.36     33.82                28.0         67.0            15.0   
e    -119.67     36.33                19.0       1241.0           244.0   
f    -119.56     36.51                37.0       1018.0           213.0   
g    -121.43     38.63                43.0       1009.0           225.0   
h    -120.65     35.48                19.0       2310.0           471.0   
i    -122.84     38.40                15.0       3080.0           617.0   
j    -118.02     34.08                31.0       2402.0           632.0   

   deposit  
a      111  
b      111  
c      111  
d      111  
e      111  
f      111  
g      111  
h      111  
i      111  
j      111

In [62]:
sm.housing_median_age

a    27.0
b    43.0
c    27.0
d    28.0
e    19.0
f    37.0
g    43.0
h    19.0
i    15.0
j    31.0
Name: housing_median_age, dtype: float64

In [63]:
type(sm.housing_median_age)

pandas.core.series.Series

In [64]:
sm.housing_median_age > 30

a    False
b     True
c    False
d    False
e    False
f     True
g     True
h    False
i    False
j     True
Name: housing_median_age, dtype: bool

In [66]:
del sm['deposit']

In [67]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
a    -122.05     37.37                27.0       3885.0           661.0
b    -118.30     34.26                43.0       1510.0           310.0
c    -117.81     33.78                27.0       3589.0           507.0
d    -118.36     33.82                28.0         67.0            15.0
e    -119.67     36.33                19.0       1241.0           244.0
f    -119.56     36.51                37.0       1018.0           213.0
g    -121.43     38.63                43.0       1009.0           225.0
h    -120.65     35.48                19.0       2310.0           471.0
i    -122.84     38.40                15.0       3080.0           617.0
j    -118.02     34.08                31.0       2402.0           632.0

In [68]:
sm.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [69]:
sm.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms'],
      dtype='object')

In [70]:
sm.sort_values(by='total_rooms')

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
d    -118.36     33.82                28.0         67.0            15.0
g    -121.43     38.63                43.0       1009.0           225.0
f    -119.56     36.51                37.0       1018.0           213.0
e    -119.67     36.33                19.0       1241.0           244.0
b    -118.30     34.26                43.0       1510.0           310.0
h    -120.65     35.48                19.0       2310.0           471.0
j    -118.02     34.08                31.0       2402.0           632.0
i    -122.84     38.40                15.0       3080.0           617.0
c    -117.81     33.78                27.0       3589.0           507.0
a    -122.05     37.37                27.0       3885.0           661.0

In [71]:
sm['total_rooms']

a    3885.0
b    1510.0
c    3589.0
d      67.0
e    1241.0
f    1018.0
g    1009.0
h    2310.0
i    3080.0
j    2402.0
Name: total_rooms, dtype: float64

In [72]:
type(sm['total_rooms'])

pandas.core.series.Series

In [73]:
sm[['total_rooms']]

total_rooms
a       3885.0
b       1510.0
c       3589.0
d         67.0
e       1241.0
f       1018.0
g       1009.0
h       2310.0
i       3080.0
j       2402.0

In [74]:
type(sm[['total_rooms']])

pandas.core.frame.DataFrame

In [75]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
a    -122.05     37.37                27.0       3885.0           661.0
b    -118.30     34.26                43.0       1510.0           310.0
c    -117.81     33.78                27.0       3589.0           507.0
d    -118.36     33.82                28.0         67.0            15.0
e    -119.67     36.33                19.0       1241.0           244.0
f    -119.56     36.51                37.0       1018.0           213.0
g    -121.43     38.63                43.0       1009.0           225.0
h    -120.65     35.48                19.0       2310.0           471.0
i    -122.84     38.40                15.0       3080.0           617.0
j    -118.02     34.08                31.0       2402.0           632.0

In [78]:
sm[['total_rooms']] > 68

total_rooms
a         True
b         True
c         True
d        False
e         True
f         True
g         True
h         True
i         True
j         True

In [83]:
sm[['total_rooms']][sm['total_rooms'] > 2000]

total_rooms
a       3885.0
c       3589.0
h       2310.0
i       3080.0
j       2402.0

In [100]:
sm

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
a    -122.05     37.37                27.0       3885.0           661.0
b    -118.30     34.26                43.0       1510.0           310.0
c    -117.81     33.78                27.0       3589.0           507.0
d    -118.36     33.82                28.0         67.0            15.0
e    -119.67     36.33                19.0       1241.0           244.0
f    -119.56     36.51                37.0       1018.0           213.0
g    -121.43     38.63                43.0       1009.0           225.0
h    -120.65     35.48                19.0       2310.0           471.0
i    -122.84     38.40                15.0       3080.0           617.0
j    -118.02     34.08                31.0       2402.0           632.0

In [102]:
sm.loc[["a", "b"]]

longitude  latitude  housing_median_age  total_rooms  total_bedrooms
a    -122.05     37.37                27.0       3885.0           661.0
b    -118.30     34.26                43.0       1510.0           310.0