<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Section 1 Homework

In [3]:
import numpy as np

In [11]:
weights = [-0.5, 0.5, 1]

In [12]:
input = [10, 15, 1]

In [16]:
def feedforward(weights, input):
    sum = 0
    for i in range(len(weights)):
        sum += weights[i] * input[i]
    return activatetor(sum)

In [17]:
def activatetor(sum):
    if sum > 0:
        return 1
    else:
        return -1

In [18]:
feedforward(weights, input)

1

Section 2 Homework

In [2]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd

In [3]:
data_link = "https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt"
col_names = ["variance", "skewness", "curtosis", "entropy", "class"]

bankdata = pd.read_csv(data_link, names=col_names, sep=",", header=None)
bankdata.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
X_train, X_test, y_train, y_test = train_test_split(bankdata.drop("class", axis=1), bankdata["class"], test_size=0.2)

Linear Kernel

In [5]:
svclassifier = SVC(kernel="linear")
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

In [6]:
y_pred = svclassifier.predict(X_test)

In [7]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[162   3]
 [  0 110]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       165
           1       0.97      1.00      0.99       110

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



Poly Kernel

In [8]:
svclassifier = SVC(kernel="poly", degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [9]:
y_pred = svclassifier.predict(X_test)

In [10]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 95  70]
 [  0 110]]
              precision    recall  f1-score   support

           0       1.00      0.58      0.73       165
           1       0.61      1.00      0.76       110

    accuracy                           0.75       275
   macro avg       0.81      0.79      0.74       275
weighted avg       0.84      0.75      0.74       275



RBF Kernel

In [12]:
svclassifier = SVC(kernel = "rbf", gamma=0.008, C = 0.1, random_state=1)
svclassifier.fit(X_train, y_train)

SVC(C=0.1, gamma=0.008, random_state=1)

In [13]:
y_pred = svclassifier.predict(X_test)

In [14]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[158   7]
 [  0 110]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       165
           1       0.94      1.00      0.97       110

    accuracy                           0.97       275
   macro avg       0.97      0.98      0.97       275
weighted avg       0.98      0.97      0.97       275

