<a href="https://colab.research.google.com/github/akbarjon2000/DataScience/blob/main/uniqueness_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
names  = np.array(['a', 'b', 'c', 'a', 'd', 'c'])

In [3]:
np.unique(names)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [4]:
set(names)

{'a', 'b', 'c', 'd'}

In [10]:
arr1 = np.array([1,2,3,4,5,6, 1])
arr2 = np.array([2,3,4,56,43,32,4,5,6,7])

In [11]:
np.in1d(arr1, arr2)

array([False,  True,  True,  True,  True,  True, False])

In [12]:
np.setdiff1d(arr1, arr2)

array([1])

In [13]:
np.save('data', arr1)

In [15]:
np.load('data.npy')

array([1, 2, 3, 4, 5, 6, 1])

In [16]:
np.savez('arrays', a = arr1, b = arr2)

In [17]:
np.load('arrays.npz')

In [18]:
arrays = np.load('arrays.npz')

In [19]:
arrays['a']

array([1, 2, 3, 4, 5, 6, 1])

In [20]:
arrays['b']

array([ 2,  3,  4, 56, 43, 32,  4,  5,  6,  7])

In [21]:
np.savez_compressed('arrays_compressed', a = arr1, b = arr2)

In [22]:
np.load('arrays_compressed.npz')

In [24]:
compressed = np.load('arrays_compressed.npz')

In [27]:
compressed['a']

array([1, 2, 3, 4, 5, 6, 1])

In [28]:
compressed['b']

array([ 2,  3,  4, 56, 43, 32,  4,  5,  6,  7])

In [30]:
a = np.array([[9,11,2], [3,1,0]])
b = np.array([[1,2], [4,5], [6,7]])

In [33]:
np.dot(a,b)

array([[65, 87],
       [ 7, 11]])